title: "QinAI Studio"
description: "Human-first AI Agents for real-world impact"
theme: null

# Favicon
favicon: /favicon.ico

# Top navigation menu (optional)
header_pages:
  - index.md
  - privacy.md
  - tos.md

# Custom includes (favicon + footer)
# head-custom.html will insert the favicon
# footer.html will override the default GitHub Pages footer
plugins:
  - jekyll-include-cache



