title: "QinAI Studio"
description: ""   # leave blank to avoid repeat footer text
theme: minima

header_pages:
  - index.md
  - privacy.md
  - tos.md


footer_content: "© 2025 QinAI Studio. All rights reserved."

